[workspace]
resolver = "2"
members = [
    "openblas-pthreads",
    "openblas-gomp",
    "openblas-pthreads-dyload",
    "openblas-gomp-dyload",
]

[workspace.package]
edition = "2021"

[profile.dev]
opt-level = 2
